# Generated by Django 3.2.9 on 2021-12-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=45)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Comments', models.TextField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalHotel.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalHotel.owner'),
        ),
        migrations.AddField(
            model_name='animal',
            name='Species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalHotel.species'),
        ),
    ]
