# Generated by Django 3.2.8 on 2022-01-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalHotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('comments', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalHotel.animal')),
            ],
        ),
    ]
